JdyyDictURL = "/camel/rest/jdyy/dicts"
JdyyDictsTypesListURL = "/camel/rest/jdyy/dicts/types/list"


#统计录入
JdyystatURL = "/camel/rest/jdyy/statisticss"
jdyyStatBtnPermissionPrefix = "jdyy:jdyyIupModule:jdyyTenMenu:"
#病员信息
JdyypatientsURL = "/camel/rest/jdyy/patientss"
jdyyPatientsBtnPermissionPrefix = "jdyy:jdyyIupModule:jdyyTenMenu:"
#就诊信息
JdyyvisitURL = "/camel/rest/jdyy/visits"
#就诊信息图片
visPatUrl = "/camel/rest/jdyy/visits/getAllByUserId"
#术式
JdyysurURL = "/camel/rest/jdyy/surgicals"
jdyySurBtnPermissionPrefix = "jdyy:jdyyDiaSurModule:jdyySurMenu:"
#诊断
JdyydiaURL = "/camel/rest/jdyy/diagnosiss"
jdyyDiaBtnPermissionPrefix = "jdyy:jdyyDiaSurModule:jdyyDiaMenu:"
#全髋
JdyyhipURL = "/camel/rest/jdyy/hips"
jdyyHipBtnPermissionPrefix = "jdyy:jdyyInvModule:jdyyHipMenu:"
#全膝
JdyykneeURL = "/camel/rest/jdyy/knees"
jdyyKneeBtnPermissionPrefix = "jdyy:jdyyInvModule:jdyyKneeMenu:"

